//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Include
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPhoneNumber
    {
        public System.Guid ID { get; set; }
        public System.Guid AccountID { get; set; }
        public byte PhoneNumberType { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExtension { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
