//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Include
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountPhoneNumbers = new HashSet<AccountPhoneNumber>();
            this.Orders = new HashSet<Order>();
        }
    
        public System.Guid ID { get; set; }
        public string Username { get; set; }
        public string HashPassword { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public byte AccountStatus { get; set; }
        public byte AccountType { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedTime { get; set; }
        public string New_LastLoginPage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPhoneNumber> AccountPhoneNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
