//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Include
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionRecord
    {
        public System.Guid ID { get; set; }
        public System.Guid TicketID { get; set; }
        public System.Guid MuseumID { get; set; }
        public System.DateTimeOffset RecordTime { get; set; }
        public bool IsRejected { get; set; }
    
        public virtual Museum Museum { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
