//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Include
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.AdmissionRecords = new HashSet<AdmissionRecord>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public string Number { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public byte Age { get; set; }
        public Nullable<System.DateTimeOffset> EffectiveTimeStart { get; set; }
        public Nullable<System.DateTimeOffset> EffectiveTimeLastActivateFrom { get; set; }
        public Nullable<System.DateTimeOffset> EffectiveTimeEnd { get; set; }
        public decimal Amount { get; set; }
        public byte AppliedAgeType { get; set; }
        public byte AppliedDurationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionRecord> AdmissionRecords { get; set; }
        public virtual Order Order { get; set; }
    }
}
